version: '3'

services:
    db:
        image: postgres
        restart: always
        env_file: .env_db
        ports:
            - 5432:5432
    piano-songs:
        build: api/
        image: "gmgalvan/api-piano-songs"
        ports:
            - 8080:8080
        env_file: .env
        depends_on:
            - db
        links:
            - "db:localhost"